export { default as Dashboard } from "./Dashbord";
export { default as Kanban } from "./Kanban";
export { default as Employees } from "./Employees";
export { default as Editor } from "./Editor";
export { default as ToolingTracking } from "./ToolingTracking";
export { default as Tooling } from "./Tooling/Tooling";
export { default as ToolingExitForm } from "./Tooling/ToolingExitForm";
export { default as Scheduler } from "./Scheduler";
// export { default as Area } from "./Charts/Area";
// export { default as Bar } from "./Charts/Bar";
// export { default as ColorMapping } from "./Charts/ColorMapping";
// export { default as Financial } from "./Charts/Financial";
// export { default as Line } from "./Charts/Line";
// export { default as Pie } from "./Charts/Pie";
// export { default as Pyramid } from "./Charts/Pyramid";
// export { default as Stacked } from "./Charts/Stacked";
export { default as Chat } from "./chat/Chat";
export { default as AIChat } from "./AIChat";
export { default as Login } from "../pages/auth/login/Login";
export { default as SingUp } from "./SignUp";
export { default as Profile } from "../pages/profile/Profile";
export { default as EditProfileModal } from "../pages/profile/EditProfileModal";
export { default as UserKanban } from "../pages/kanban/UserKanban";
